version: '3.4'
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: akeneo_pim
      MYSQL_USER: akeneo_pim
      MYSQL_PASSWORD: akeneo_pim
  php:
    image: akeneo/fpm:php-7.3
    depends_on:
      - mysql
    volumes:
      - ./:/srv/pim
    environment:
      APP_ENV: dev
  apache:
    image: httpd:2.4
    depends_on:
      - php
      - node
    volumes:
      - ./:/srv/pim:ro
    ports:
      - '8080:80'
  node:
    image: akeneo/node:10
    depends_on:
      - php
    volumes:
      - ./:/srv/pim
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
